ADAPTDCTR-27: Flex box component example
SU-SWS/decanter-web pull request #133
Opened 2023-04-19 22:06 UTC by Lyafel

# Summary
- TL;DR - what's this PR for?

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2023-04-21 18:24 UTC, yvonnetangsu requested changes
@Lyafel This is heading in a good direction - I like how you listed the available option. Could we have some visual examples. We're thinking something along the line of these (boxes in a row/column). Perhaps with demos on how to use the alignment classes too? 😄 Thanks in advance!
https://tailwindcss.com/docs/flex-direction

2023-05-15 17:00 UTC, jdwjdwjdw requested changes
Hi @Lyafel! @yvonnetangsu and I discussed our vision for the examples section and decided to change a number of things. For this flexbox PR, we decided to change the page to “Cards” and list a few example cards created within the decanter ecosystem. Can you remove the current content, update the title to “Cards”, and show three card examples (from our sites) and their related HTML code? Three cards that would work could be the “Stories”, “Travel/Study”, and Basic Card (in the “Programming With a Purpose” section) on the [alumni site](https://alumni.stanford.edu/). Thanks!

2023-05-24 06:22 UTC, jdwjdwjdw requested changes
Thanks @Lyafel! I'm liking the changes, just a couple of fixups needed.

2023-05-24 06:22 UTC, jdwjdwjdw commented on content/examples/cards.mdx
> +lastUpdatedDate: 2022-05-17T12:00:00.000Z
Can you update this to 2023?

2023-05-24 06:22 UTC, jdwjdwjdw commented on content/examples/cards.mdx
> +<div className="su-max-w-1200">
Can you update this max-width to `lg:su-max-w-600 xl:su-max-w-800 2xl:su-max-w-1000`? That should address the code block width, as well as constrain the width of the card examples.

2023-05-24 06:22 UTC, jdwjdwjdw commented on content/examples/cards.mdx
> +
Can you remove the space at the top of this code block?

2023-05-24 06:22 UTC, jdwjdwjdw commented on content/examples/cards.mdx
> +  <Section heading="Travel/Study" width="full" className="su-max-w-1200">
Can you adjust this section heading to `Alumni Travel/Study Card`?

2023-05-24 06:22 UTC, jdwjdwjdw commented on content/examples/cards.mdx
> +  <Section heading="Stories" width="full" className="su-max-w-1200">
Can you adjust this section heading to `Alumni Story Card`?

2023-05-24 06:22 UTC, jdwjdwjdw commented on content/examples/cards.mdx
> +  <Section heading="Basic Card" width="full" className="su-max-w-1200">
Can you adjust this section heading to `Alumni Basic Card`?

2023-05-24 06:22 UTC, jdwjdwjdw commented on tailwind.config.js
Since we're showing examples of what cards can look like without additional config, let's go ahead and not extend our tailwind. And then can you update the card examples / code blocks, replacing the saa-specific styles with a close matching non-saa styles?

2023-09-01 22:34 UTC, merged